### ISSUE TITLE
Testing `DeserializeSeed` using `serde_test`

### ISSUE THREAD

**Issue by Anders429** [serde-rs/test#24]
Is there any way to test types that implement `DeserializeSeed`, as opposed to `Deserialize`, using the `serde_test` crate? I am looking for some equivalent of `assert_de_tokens`, but that would accept the seed as well to test stateful deserialization. Perhaps something like a `assert_de_seed_tokens` or similar?

I would love to know if such a thing exists or if there are any workarounds that can be used to test `DeserializeSeed` types with the current tools.

**Comment by dtolnay** [comment]
I notice https://github.com/Anders429/serde_assert now exists. Thanks!
